## This Notebook will be used to make analytical operations with documented outcomes and insights.

We start by importing the different libraries and setting up a path finder for future functions imports

In [1]:
#importing necessary libraries and setting up paths. do not update this cell. Run first before running any other cell. 
import sys
from pathlib import Path

sys.path.append(str(Path("..").resolve()))

analytics_path = Path("../data/analytics")
session_path = (analytics_path / "session_analytics.parquet").as_posix()
visitor_path = (analytics_path / "visitor_analytics.parquet").as_posix()
question_path = (analytics_path / "question_analytics.parquet").as_posix()


This first operation highlights the campaigns overview and the outcomes distribution.

32.9% of sessions remain incomplete.  
We also conclude the outcomes distribution: 70% represent no current indication; 20% are possibly at risk; 10% already are diagnosed with diabetes.  
We also have a number of 2800 returning visitors that have had multiple sessions.

In [2]:
from src.analytics.campaign_overview import (
    get_campaign_overview,
    get_outcome_distribution
)

display(get_campaign_overview(session_path))
display(get_outcome_distribution(session_path))

,unique_visitors,total_sessions,started_questionnaires,completed_questionnaires,completion_rate,returning_visitors
0,19825,25475,16313.0,10946.0,67.1,2825

        outcome_category  total  percentage
0  no_current_indication   7674       70.11
1          possible_risk   2212       20.21
2     declared_diagnosed   1060        9.68

This operation uses the results of the previous one to determine the starting rate for each visitor (takes account of visitors that have started multiple sessions) which is 66.17%.  
Only 66.17% of visitors start the questionnaire.

In [3]:
from src.analytics.campaign_overview import get_visitor_start_rate

display(get_visitor_start_rate(session_path))

   visitors_started  visitor_start_rate
0             13118               66.17

This next operation highlights the audience differences in outcomes. 


Outcomes are really similar across all genders but differ a lot across age groups which is expected. The average age of each outcome being: 51 diagnosed; 50 at risk; 41.4 no current indication.


Relatively few visitors ommited sharing personnal data which is not a problem, the number is not consequent to influence data.  
A returning visitor factor may not be a poroblem since the completion rate across all ages is the same, which is around 0.56 session completed per person.


The campaign reached visitors across all age groups, with 35-44 and 45-54 being the most represented as they form half of the completed sessions.  
No real influence detected regarding the region. Ages across regions are the same and we can say the same thing about genders, some regions have a higher female percentage but the number of individuals is not consequent to conclude anything.

In [4]:
from src.analytics.audience import (
    outcome_by_age,
    outcome_by_gender,
    outcome_by_region,
    age_by_outcome,
    missing_demographics,
    median_age_by_region,
    visitors_by_age_group,
    completed_sessions_by_age,
    gender_by_region
)

display(outcome_by_age(session_path))
display(outcome_by_gender(session_path))
display(outcome_by_region(session_path))
display(gender_by_region(visitor_path))
display(age_by_outcome(session_path))
display(visitors_by_age_group(visitor_path))
display(missing_demographics(visitor_path))
display(median_age_by_region(visitor_path))
display(completed_sessions_by_age(visitor_path))

   age_group       outcome_category  total  percentage
0      16-24  no_current_indication   1028       87.79
1      16-24          possible_risk    105        8.97
2      16-24     declared_diagnosed     38        3.25
3      25-34  no_current_indication   1456       82.03
4      25-34          possible_risk    221       12.45
5      25-34     declared_diagnosed     98        5.52
6      35-44  no_current_indication   1931       75.34
7      35-44          possible_risk    428       16.70
8      35-44     declared_diagnosed    204        7.96
9      45-54  no_current_indication   1612       66.64
10     45-54          possible_risk    548       22.65
11     45-54     declared_diagnosed    259       10.71
12     55-64  no_current_indication    875       54.62
13     55-64          possible_risk    490       30.59
14     55-64     declared_diagnosed    237       14.79
15       65+  no_current_indication    488       47.61
16       65+          possible_risk    354       34.54
17       65+     declared_diagnosed    183       17.85

               gender       outcome_category  total  percentage
0              female  no_current_indication   3717       69.28
1              female          possible_risk   1117       20.82
2              female     declared_diagnosed    531        9.90
3                male  no_current_indication   3390       70.73
4                male          possible_risk    935       19.51
5                male     declared_diagnosed    468        9.76
6        not provided  no_current_indication    238       70.83
7        not provided          possible_risk     69       20.54
8        not provided     declared_diagnosed     29        8.63
9               other  no_current_indication    103       74.64
10              other          possible_risk     23       16.67
11              other     declared_diagnosed     12        8.70
12  prefer_not_to_say  no_current_indication    226       71.97
13  prefer_not_to_say          possible_risk     68       21.66
14  prefer_not_to_say     declared_diagnosed     20        6.37

                        region       outcome_category  total  percentage
0         auvergne-rhone-alpes  no_current_indication    845       70.30
1         auvergne-rhone-alpes          possible_risk    235       19.55
2         auvergne-rhone-alpes     declared_diagnosed    122       10.15
3                     bretagne  no_current_indication    802       68.90
4                     bretagne          possible_risk    250       21.48
5                     bretagne     declared_diagnosed    112        9.62
6                    grand-est  no_current_indication    807       71.73
7                    grand-est          possible_risk    209       18.58
8                    grand-est     declared_diagnosed    109        9.69
9              hauts-de-france  no_current_indication    836       69.78
10             hauts-de-france          possible_risk    242       20.20
11             hauts-de-france     declared_diagnosed    120       10.02
12               ile-de-france  no_current_indication    836       70.61
13               ile-de-france          possible_risk    231       19.51
14               ile-de-france     declared_diagnosed    117        9.88
15                not provided  no_current_indication    281       71.68
16                not provided          possible_risk     71       18.11
17                not provided     declared_diagnosed     40       10.20
18          nouvelle-aquitaine  no_current_indication    842       69.76
19          nouvelle-aquitaine          possible_risk    254       21.04
20          nouvelle-aquitaine     declared_diagnosed    111        9.20
21                   occitanie  no_current_indication    819       69.35
22                   occitanie          possible_risk    245       20.75
23                   occitanie     declared_diagnosed    117        9.91
24            pays-de-la-loire  no_current_indication    794       70.08
25            pays-de-la-loire          possible_risk    236       20.83
26            pays-de-la-loire     declared_diagnosed    103        9.09
27  provence-alpes-cote-d'azur  no_current_indication    812       70.00
28  provence-alpes-cote-d'azur          possible_risk    239       20.60
29  provence-alpes-cote-d'azur     declared_diagnosed    109        9.40

                        region             gender  visitors  percentage
0         auvergne-rhone-alpes             female      1056       48.87
1         auvergne-rhone-alpes               male       947       43.82
2         auvergne-rhone-alpes       not provided        70        3.24
3         auvergne-rhone-alpes  prefer_not_to_say        58        2.68
4         auvergne-rhone-alpes              other        30        1.39
5                     bretagne             female      1018       48.66
6                     bretagne               male       917       43.83
7                     bretagne       not provided        72        3.44
8                     bretagne  prefer_not_to_say        55        2.63
9                     bretagne              other        30        1.43
10                   grand-est             female      1094       51.92
11                   grand-est               male       878       41.67
12                   grand-est       not provided        56        2.66
13                   grand-est  prefer_not_to_say        53        2.52
14                   grand-est              other        26        1.23
15             hauts-de-france             female      1106       50.43
16             hauts-de-france               male       950       43.32
17             hauts-de-france       not provided        57        2.60
18             hauts-de-france  prefer_not_to_say        54        2.46
19             hauts-de-france              other        26        1.19
20               ile-de-france             female      1053       48.57
21               ile-de-france               male       949       43.77
22               ile-de-france       not provided        72        3.32
23               ile-de-france  prefer_not_to_say        51        2.35
24               ile-de-france              other        43        1.98
25                not provided             female       365       45.80
26                not provided               male       362       45.42
27                not provided       not provided        46        5.77
28                not provided  prefer_not_to_say        17        2.13
29                not provided              other         7        0.88
30          nouvelle-aquitaine             female      1034       49.29
31          nouvelle-aquitaine               male       925       44.09
32          nouvelle-aquitaine  prefer_not_to_say        58        2.76
33          nouvelle-aquitaine       not provided        53        2.53
34          nouvelle-aquitaine              other        28        1.33
35                   occitanie             female      1008       47.73
36                   occitanie               male       945       44.74
37                   occitanie       not provided        65        3.08
38                   occitanie  prefer_not_to_say        58        2.75
39                   occitanie              other        36        1.70
40            pays-de-la-loire             female       971       47.95
41            pays-de-la-loire               male       884       43.65
42            pays-de-la-loire       not provided        75        3.70
43            pays-de-la-loire  prefer_not_to_say        60        2.96
44            pays-de-la-loire              other        35        1.73
45  provence-alpes-cote-d'azur             female      1011       48.79
46  provence-alpes-cote-d'azur               male       916       44.21
47  provence-alpes-cote-d'azur       not provided        79        3.81
48  provence-alpes-cote-d'azur  prefer_not_to_say        44        2.12
49  provence-alpes-cote-d'azur              other        22        1.06

        outcome_category  average_age  median_age
0  no_current_indication         41.4        41.0
1     declared_diagnosed         51.0        51.0
2          possible_risk         50.0        50.0

  age_group  visitors
0     35-44      4553
1     45-54      4349
2     25-34      3185
3     55-64      2890
4     16-24      2127
5       65+      1969

   missing_age  missing_gender  missing_region
0          752             645             797

                       region  median_age
0               ile-de-france        44.5
1        auvergne-rhone-alpes        44.0
2             hauts-de-france        44.0
3                   occitanie        44.0
4                    bretagne        44.0
5            pays-de-la-loire        44.0
6          nouvelle-aquitaine        44.0
7                   grand-est        43.0
8  provence-alpes-cote-d'azur        43.0
9                not provided        40.0

  age_group  visitors  completed_sessions  avg_completed_per_visitor
0     25-34      3185              1775.0                       0.56
1     35-44      4553              2563.0                       0.56
2     45-54      4349              2419.0                       0.56
3     55-64      2890              1602.0                       0.55
4     16-24      2127              1171.0                       0.55
5       65+      1969              1025.0                       0.52

This next operation hightlights campaigns performance to analyse which campaign succeeded the most in term of completion and user interaction.  

After comparing different campaigns all of them had they same number of people except for "diabetes_retargeting" which had significantly less visitors but overperformed relatively to others regarding the sessions started and completed. Also most of the sessions had no campaign name which is unfortunate.  
All of the campaigns had almost the same outcome distribution except for "diabetes_45plus" and "diabetes_social_awareness" which suggest further analysis.  
Further analysis reveals that "diabetes_45plus" had a higher average visitor age while "diabetes_social_awareness" presents a lower average visitor age, which explains the difference in outcomes provides by each one.  

For the acquisition sources, social media sources underperform but the results cannot be interpreted since the numbrer of sessions is little compared to the whole study case. In the otherhand "google-organic" and "google-ads" perform well and have the highest started sessions count across all sources, "chatgpt", "refferal" and "email" detain the most efficient results, relatively high session count, higher start rate and excellent completion rate. acquisition source does not seem to have any link of influence with the outcomes  

We notice that mobile users visit the most the campaigns but it comes at a cost, mobile users have the least completion rate across all devices. In the other hand Desktop as a device type hold a nice balance between sessions and completion, tablet is not really used across visitors but it still hold a respectable completion rate. Further analysis should be done to inspect if there is any correlation between devices used and outcomes (even if there is, it does not mean that there is any causation).  

Further analysis concludes that there is no correlation between devices used and outcomes provided.

In [5]:
from src.analytics.campaign_performance import (
    performance_by,
    outcomes_by,
    age_by_campaign,
    device_by_source,
    outcomes_by_device,
)

display(performance_by(session_path, "campaign_name"))
display(outcomes_by(session_path, "campaign_name"))
display(performance_by(session_path, "acquisition_source"))
display(outcomes_by(session_path, "acquisition_source"))
display(performance_by(session_path, "device_type"))
display(device_by_source(session_path))
display(age_by_campaign(session_path))
display(outcomes_by_device(session_path))

,campaign_name,sessions,started,completed,completion_rate,dropout_rate
0,NaN,13808,9242.0,6388.0,69.12,30.88
1,diabetes_awareness_general,3356,2222.0,1501.0,67.55,32.45
2,diabetes_social_awareness,3314,1666.0,934.0,56.06,43.94
3,diabetes_45plus,3292,1911.0,1214.0,63.53,36.47
4,diabetes_retargeting,1705,1272.0,909.0,71.46,28.54

                 campaign_name       outcome_category  total  percentage
0              diabetes_45plus          possible_risk    483       39.79
1              diabetes_45plus  no_current_indication    475       39.13
2              diabetes_45plus     declared_diagnosed    256       21.09
3   diabetes_awareness_general  no_current_indication   1096       73.02
4   diabetes_awareness_general          possible_risk    263       17.52
5   diabetes_awareness_general     declared_diagnosed    142        9.46
6         diabetes_retargeting  no_current_indication    657       72.28
7         diabetes_retargeting          possible_risk    177       19.47
8         diabetes_retargeting     declared_diagnosed     75        8.25
9    diabetes_social_awareness  no_current_indication    732       78.37
10   diabetes_social_awareness          possible_risk    141       15.10
11   diabetes_social_awareness     declared_diagnosed     61        6.53
12                         NaN  no_current_indication   4714       73.79
13                         NaN          possible_risk   1148       17.97
14                         NaN     declared_diagnosed    526        8.23

,acquisition_source,sessions,started,completed,completion_rate,dropout_rate
0,google-organic,6472,4075.0,2753.0,67.56,32.44
1,google-ads,6271,3748.0,2408.0,64.25,35.75
2,social,3140,1607.0,907.0,56.44,43.56
3,chatgpt,2505,1850.0,1301.0,70.32,29.68
4,referral,1750,1393.0,1045.0,75.02,24.98
5,email,1617,1350.0,1028.0,76.15,23.85
6,direct,1571,1009.0,677.0,67.10,32.90
7,google,884,555.0,374.0,67.39,32.61
8,other,665,376.0,247.0,65.69,34.31
9,facebook,220,101.0,46.0,45.54,54.46
10,instagram,219,119.0,66.0,55.46,44.54
11,ai-assistant,161,130.0,94.0,72.31,27.69

   acquisition_source       outcome_category  total  percentage
0        ai-assistant  no_current_indication     73       77.66
1        ai-assistant          possible_risk     15       15.96
2        ai-assistant     declared_diagnosed      6        6.38
3             chatgpt  no_current_indication   1030       79.17
4             chatgpt          possible_risk    182       13.99
5             chatgpt     declared_diagnosed     89        6.84
6              direct  no_current_indication    495       73.12
7              direct          possible_risk    131       19.35
8              direct     declared_diagnosed     51        7.53
9               email  no_current_indication    757       73.64
10              email          possible_risk    177       17.22
11              email     declared_diagnosed     94        9.14
12           facebook  no_current_indication     31       67.39
13           facebook          possible_risk     11       23.91
14           facebook     declared_diagnosed      4        8.70
15             google  no_current_indication    283       75.67
16             google          possible_risk     63       16.84
17             google     declared_diagnosed     28        7.49
18         google-ads  no_current_indication   1340       55.65
19         google-ads          possible_risk    707       29.36
20         google-ads     declared_diagnosed    361       14.99
21     google-organic  no_current_indication   2004       72.79
22     google-organic          possible_risk    515       18.71
23     google-organic     declared_diagnosed    234        8.50
24          instagram  no_current_indication     55       83.33
25          instagram          possible_risk      8       12.12
26          instagram     declared_diagnosed      3        4.55
27              other  no_current_indication    179       72.47
28              other          possible_risk     47       19.03
29              other     declared_diagnosed     21        8.50
30           referral  no_current_indication    718       68.71
31           referral          possible_risk    219       20.96
32           referral     declared_diagnosed    108       10.33
33             social  no_current_indication    709       78.17
34             social          possible_risk    137       15.10
35             social     declared_diagnosed     61        6.73

  device_type  sessions  started  completed  completion_rate  dropout_rate
0      mobile     16468  10260.0     6436.0            62.73         37.27
1     desktop      7667   5203.0     3905.0            75.05         24.95
2      tablet      1340    850.0      605.0            71.18         28.82

   device_type acquisition_source  sessions  completion_rate
0       mobile       ai-assistant       107            70.11
1      desktop       ai-assistant        50            77.50
2       tablet       ai-assistant         4            66.67
3       mobile            chatgpt      1499            66.70
4      desktop            chatgpt       862            76.41
5       tablet            chatgpt       144            71.43
6      desktop             direct       826            71.27
7       mobile             direct       669            61.03
8       tablet             direct        76            74.47
9       mobile              email       772            72.53
10     desktop              email       763            79.25
11      tablet              email        82            81.97
12      mobile           facebook       196            44.32
13     desktop           facebook        15            55.56
14      tablet           facebook         9            50.00
15      mobile             google       497            63.26
16     desktop             google       338            73.02
17      tablet             google        49            70.37
18      mobile         google-ads      4851            62.20
19     desktop         google-ads      1081            71.04
20      tablet         google-ads       339            71.72
21      mobile     google-organic      3852            63.64
22     desktop     google-organic      2294            73.55
23      tablet     google-organic       326            70.56
24      mobile          instagram       202            55.45
25     desktop          instagram        10            60.00
26      tablet          instagram         7            50.00
27      mobile              other       379            60.45
28     desktop              other       252            73.85
29      tablet              other        34            69.23
30     desktop           referral       965            82.02
31      mobile           referral       692            65.87
32      tablet           referral        93            69.33
33      mobile             social      2752            55.54
34     desktop             social       211            61.05
35      tablet             social       177            66.28

                campaign_name  average_age  median_age  sessions
0             diabetes_45plus         59.4        59.0      3192
1        diabetes_retargeting         43.1        43.0      1627
2  diabetes_awareness_general         43.9        43.0      3256
3                         NaN         42.8        43.0     13373
4   diabetes_social_awareness         34.0        33.0      3039

  device_type       outcome_category  total  percentage
0     desktop  no_current_indication   2733       69.99
1     desktop          possible_risk    804       20.59
2     desktop     declared_diagnosed    368        9.42
3      mobile  no_current_indication   4524       70.29
4      mobile          possible_risk   1274       19.79
5      mobile     declared_diagnosed    638        9.91
6      tablet  no_current_indication    417       68.93
7      tablet          possible_risk    134       22.15
8      tablet     declared_diagnosed     54        8.93

This next operation will highlight information regarding the questionnaire and how visitors interact with it.  

We notice that most of the questions have high answer rates and little dropouts except for question 4 which has a 13.75% dropout rate, it is really high and be explained with different possibilities. we'll just make a note of it for now since i can't really explain if the reason comes from the question itself or from the questionnaires structure.  
And regarding the questionnaire structure, questions with possible "not sure" or "prefer not to say" answer have on average 8.5% of said answer, which is not bad, the questions are well structured in a way that they don't make the visitor confused or unconfortable, however the fifth question is in my opinion very confusing for people with an already given diagnosis, since they would not know how to answer it, they may understand that since they already have a diagnosis then they shoudl answer "no" or "yes" since they do have high blood sugar but got a diagnosis, i recommend that for this question we restructure answers only for people who already answer "yes" for the first question: "yes, before my diagnosis", "no, never before my diagnosis"

We cannot use questionnaire outcomes to correlate answers with real medical outcomes since the outcomes provided are results of the same questionnaire answers, so in this analysis the most important data for me will be the one of people who already had a diagnosis and then correlate their given answers with risks and reccurency.

After further analysis, people with an already given diagnosis tend to be 10% more positive to symptoms such as unusual thirst and frequent urination, while people at rist present 40% more positive answers to that same given symptom.  
Data about the physical activity question seems to be well rounded for people already diagnosed with type 2 diabetes, it could be explained by the fast that people who already received a diagnosis are more recommended to exercise for their own benefits by their health professionals. people at risk tend to be have a more sedentary lifestyle (58%) than people who aren't (13%) which is expected.
Only 32% of diagnosed people report a parent or sibling whit diagnosed type 2 diabetes which is twice as much as people with no current indicators, people at risk report twice as much as diagnosed people: 63%. I can't really interprete this data, i need more specifications about rankins, what makes a person at risk, what criteria from the questionnaire are used as base for an outcome providing, which will be my next step, try to deduct the scale used.  

After answers tendencies analysis i deduct that for a negative outcome to be provided at least 3 of these questions must get a positive answer:  
positive symptoms such as thirst and frequent urination .  
a parent or siblin with diagnosed type 2 diabetes.  
No physical activity.  
High blood sugar levels.  
Again the i have the same questions, at was stage is a symptom really considered a risk because we notice that people with diagnosis answer on average less positive to this scale than people at risk.

In [6]:
from src.analytics.questionnaire_analysis import (
    question_performance,
    responses_by_outcome,
    prefer_not_to_say
)

display(question_performance(question_path))
display(responses_by_outcome(question_path))
display(prefer_not_to_say(question_path))

,question_number,question_text,reached,answer_rate,dropouts,dropout_rate,avg_response_seconds,median_response_seconds
0,1,Have you ever been told by a healthcare profes...,15427,97.91,323.0,2.09,15.02,14.0
1,2,"During the last 3 months, have you frequently ...",15104,94.90,771.0,5.10,15.11,14.0
2,3,Has a parent or sibling been diagnosed with Ty...,14333,94.06,851.0,5.94,15.10,14.0
3,4,How often do you usually do at least 30 minute...,13482,86.24,1855.0,13.76,23.34,21.0
4,5,Have you ever been told that your blood sugar ...,11627,95.05,681.0,5.86,15.04,13.0

,question_number,answer_value,outcome_category,responses,percentage
0,1,yes,declared_diagnosed,1060,100.00
1,2,no,declared_diagnosed,689,65.00
2,2,yes,declared_diagnosed,259,24.43
3,2,not_sure,declared_diagnosed,112,10.57
4,3,no,declared_diagnosed,629,59.34
5,3,yes,declared_diagnosed,342,32.26
6,3,not_sure,declared_diagnosed,89,8.40
7,4,rarely_or_never,declared_diagnosed,316,29.81
8,4,3_to_4_days_per_week,declared_diagnosed,262,24.72
9,4,5_or_more_days_per_week,declared_diagnosed,245,23.11
10,4,1_to_2_days_per_week,declared_diagnosed,237,22.36
11,5,no,declared_diagnosed,708,66.79
12,5,yes,declared_diagnosed,273,25.75
13,5,not_sure,declared_diagnosed,79,7.45
14,1,no,no_current_indication,7352,95.80
15,1,prefer_not_to_say,no_current_indication,322,4.20
16,2,no,no_current_indication,6062,78.99
17,2,not_sure,no_current_indication,834,10.87
18,2,yes,no_current_indication,778,10.14
19,3,no,no_current_indication,5755,74.99
20,3,yes,no_current_indication,1169,15.23
21,3,not_sure,no_current_indication,750,9.77
22,4,3_to_4_days_per_week,no_current_indication,2441,31.81
23,4,1_to_2_days_per_week,no_current_indication,2163,28.19
24,4,5_or_more_days_per_week,no_current_indication,2058,26.82
25,4,rarely_or_never,no_current_indication,1012,13.19
26,5,no,no_current_indication,6153,80.18
27,5,not_sure,no_current_indication,808,10.53
28,5,yes,no_current_indication,713,9.29
29,1,no,possible_risk,2091,94.53
30,1,prefer_not_to_say,possible_risk,121,5.47
31,2,yes,possible_risk,1178,53.25
32,2,no,possible_risk,905,40.91
33,2,not_sure,possible_risk,129,5.83
34,3,yes,possible_risk,1375,62.16
35,3,no,possible_risk,746,33.73
36,3,not_sure,possible_risk,91,4.11
37,4,rarely_or_never,possible_risk,1281,57.91
38,4,1_to_2_days_per_week,possible_risk,336,15.19
39,4,3_to_4_days_per_week,possible_risk,321,14.51
40,4,5_or_more_days_per_week,possible_risk,274,12.39
41,5,yes,possible_risk,1096,49.55
42,5,no,possible_risk,965,43.63
43,5,not_sure,possible_risk,151,6.83

   question_number  total_responses  prefer_not_to_say_not_sure  percentage
0                1            15104                       611.0        4.05
1                2            14333                      1399.0        9.76
2                3            13482                      1160.0        8.60
3                4            11627                         0.0        0.00
4                5            11051                      1055.0        9.55

This next operation will leand to a further more personal analytical insights, it might provide me correlations between events and might as well have no relevant outcomes.  

For the first analysis (cell 1) i noticed that people between 35 and 44 years old with a possible risk outcome tend to stay awake late at night which could be correlated with a sedentary lifestyle, the data is little so i cannot conclude with anything, this is just an insight with no real value.  

The second analysis (cell 2) helped me notice a gain in popularity for the campaign, the compared results of June and July show a difference of 2000 new visitors, the compaign recoded 9500 new visitors for the month of June and 11500 for July. August cannot be taken into account since the campaign has been active during this month for only 2 days.  

The last analysis (cell 3) is not so relevant but we can notice a repeated pattern on the answers combinations, combinations that lead to most abandons ALWAYS contains a "no" answer, in my opinion people don't really identify to the topic and just leave the questionnaire, or some may not find it entertaining and so they leave after repeative negative answers.

In [7]:
#Cell 1
#this cell shows the outcomes regarding the time of the day the session was completed and age groups of visitors.
from src.analytics.audience import (
    outcomes_by_age_and_time,
)
result = outcomes_by_age_and_time(session_path)

for age_group in ["16-24", "25-34", "35-44", "45-54", "55-64", "65+"]:
    print(f"\nAge group: {age_group}")
    display(
        result[result["age_group"] == age_group]
        [["session_period", "outcome_category", "total_sessions", "percentage"]]
    )

Age group: 16-24

   session_period       outcome_category  total_sessions  percentage
0       Afternoon  no_current_indication             254       87.89
1       Afternoon          possible_risk              24        8.30
2       Afternoon     declared_diagnosed              11        3.81
3             Day  no_current_indication             245       86.27
4             Day          possible_risk              29       10.21
5             Day     declared_diagnosed              10        3.52
6      Late Night  no_current_indication             216       88.89
7      Late Night          possible_risk              19        7.82
8      Late Night     declared_diagnosed               8        3.29
9         Morning  no_current_indication             225       87.89
10        Morning          possible_risk              22        8.59
11        Morning     declared_diagnosed               9        3.52
12          Night  no_current_indication              88       88.89
13          Night          possible_risk              11       11.11

Age group: 25-34

   session_period       outcome_category  total_sessions  percentage
14      Afternoon  no_current_indication             352       80.18
15      Afternoon          possible_risk              62       14.12
16      Afternoon     declared_diagnosed              25        5.69
17            Day  no_current_indication             367       81.92
18            Day          possible_risk              56       12.50
19            Day     declared_diagnosed              25        5.58
20     Late Night  no_current_indication             302       86.04
21     Late Night          possible_risk              33        9.40
22     Late Night     declared_diagnosed              16        4.56
23        Morning  no_current_indication             299       80.59
24        Morning          possible_risk              47       12.67
25        Morning     declared_diagnosed              25        6.74
26          Night  no_current_indication             136       81.93
27          Night          possible_risk              23       13.86
28          Night     declared_diagnosed               7        4.22

Age group: 35-44

   session_period       outcome_category  total_sessions  percentage
29      Afternoon  no_current_indication             502       76.06
30      Afternoon          possible_risk             103       15.61
31      Afternoon     declared_diagnosed              55        8.33
32            Day  no_current_indication             495       78.82
33            Day          possible_risk              92       14.65
34            Day     declared_diagnosed              41        6.53
35     Late Night  no_current_indication             373       70.51
36     Late Night          possible_risk             109       20.60
37     Late Night     declared_diagnosed              47        8.88
38        Morning  no_current_indication             421       76.13
39        Morning          possible_risk              91       16.46
40        Morning     declared_diagnosed              41        7.41
41          Night  no_current_indication             140       72.54
42          Night          possible_risk              33       17.10
43          Night     declared_diagnosed              20       10.36

Age group: 45-54

   session_period       outcome_category  total_sessions  percentage
44      Afternoon  no_current_indication             377       64.33
45      Afternoon          possible_risk             133       22.70
46      Afternoon     declared_diagnosed              76       12.97
47            Day  no_current_indication             409       66.94
48            Day          possible_risk             146       23.90
49            Day     declared_diagnosed              56        9.17
50     Late Night  no_current_indication             344       67.19
51     Late Night          possible_risk             123       24.02
52     Late Night     declared_diagnosed              45        8.79
53        Morning  no_current_indication             347       67.91
54        Morning          possible_risk             106       20.74
55        Morning     declared_diagnosed              58       11.35
56          Night  no_current_indication             135       67.84
57          Night          possible_risk              40       20.10
58          Night     declared_diagnosed              24       12.06

Age group: 55-64

   session_period       outcome_category  total_sessions  percentage
59      Afternoon  no_current_indication             232       53.33
60      Afternoon          possible_risk             131       30.11
61      Afternoon     declared_diagnosed              72       16.55
62            Day  no_current_indication             194       52.86
63            Day          possible_risk             119       32.43
64            Day     declared_diagnosed              54       14.71
65     Late Night  no_current_indication             191       57.88
66     Late Night          possible_risk              99       30.00
67     Late Night     declared_diagnosed              40       12.12
68        Morning  no_current_indication             199       57.18
69        Morning          possible_risk             104       29.89
70        Morning     declared_diagnosed              45       12.93
71          Night  no_current_indication              59       48.36
72          Night          possible_risk              37       30.33
73          Night     declared_diagnosed              26       21.31

Age group: 65+

   session_period       outcome_category  total_sessions  percentage
74      Afternoon  no_current_indication             107       45.92
75      Afternoon          possible_risk              82       35.19
76      Afternoon     declared_diagnosed              44       18.88
77            Day  no_current_indication             137       47.74
78            Day          possible_risk             103       35.89
79            Day     declared_diagnosed              47       16.38
80     Late Night  no_current_indication             102       49.04
81     Late Night          possible_risk              68       32.69
82     Late Night     declared_diagnosed              38       18.27
83        Morning  no_current_indication             104       49.06
84        Morning          possible_risk              70       33.02
85        Morning     declared_diagnosed              38       17.92
86          Night  no_current_indication              38       44.71
87          Night          possible_risk              31       36.47
88          Night     declared_diagnosed              16       18.82

In [8]:
#Cell 2
#this cell shows the monthly evolution of outcomes and sessions over time.
from src.analytics.campaign_performance import (
    monthly_outcome_evolution,
    monthly_session_evolution
)

display(monthly_outcome_evolution(session_path))
display(monthly_session_evolution(session_path))

     month       outcome_category  total  percentage
0  2026-06     declared_diagnosed    356        8.23
1  2026-06  no_current_indication   3210       74.17
2  2026-06          possible_risk    762       17.61
3  2026-07     declared_diagnosed    668       10.53
4  2026-07  no_current_indication   4280       67.47
5  2026-07          possible_risk   1396       22.01
6  2026-08     declared_diagnosed     36       13.14
7  2026-08  no_current_indication    184       67.15
8  2026-08          possible_risk     54       19.71

     month  sessions  unique_visitors
0  2026-06     10418             9470
1  2026-07     14381            11541
2  2026-08       676              676

In [9]:
#cell 3
#this cell shows the most frequent combinations of questions that lead to dropouts in the questionnaire.
from src.analytics.questionnaire_analysis import (
    frequent_dropout_combinations
)

display(frequent_dropout_combinations(question_path))

,answer_combination,answered_questions,last_question,sessions,percentage
0,Q1: no | Q2: no | Q3: no,3,3,734,17.65
1,Q1: no,1,1,657,15.80
2,Q1: no | Q2: no,2,2,499,12.00
3,Q1: no | Q2: no | Q3: yes,3,3,293,7.05
4,Q1: no | Q2: yes | Q3: no,3,3,195,4.69
5,Q1: no | Q2: yes,2,2,144,3.46
6,Q1: no | Q2: yes | Q3: yes,3,3,103,2.48
7,Q1: no | Q2: no | Q3: not_sure,3,3,102,2.45
8,Q1: yes,1,1,89,2.14
9,Q1: no | Q2: not_sure | Q3: no,3,3,85,2.04
10,Q1: yes | Q2: no,2,2,81,1.95
11,Q1: yes | Q2: no | Q3: no,3,3,80,1.92
12,Q1: no | Q2: no | Q3: no | Q4: 5_or_more_days_...,4,4,59,1.42
13,Q1: no | Q2: no | Q3: no | Q4: 3_to_4_days_per...,4,4,58,1.39
14,Q1: no | Q2: not_sure,2,2,57,1.37
15,Q1: no | Q2: no | Q3: no | Q4: 1_to_2_days_per...,4,4,56,1.35
16,Q1: no | Q2: not_sure | Q3: yes,3,3,49,1.18
17,Q1: no | Q2: no | Q3: no | Q4: rarely_or_never,4,4,36,0.87
18,Q1: yes | Q2: yes | Q3: no,3,3,36,0.87
19,Q1: prefer_not_to_say | Q2: no | Q3: no,3,3,34,0.82